export const FEATURES = [
  {
    type: 0,
    name: "Background",
    assets: [
      "/backgrounds/0.png",
      "/backgrounds/1.png",
      "/backgrounds/2.png",
      "/backgrounds/3.png",
    ],
  },
  {
    type: 1,
    name: "Skin/expression",
    assets: [
      "/facial-variations/0.png",
      "/facial-variations/1.png",
      "/facial-variations/2.png",
      "/facial-variations/3.png",
      "/facial-variations/4.png",
      "/facial-variations/5.png",
      "/facial-variations/6.png",
      "/facial-variations/7.png",
      "/facial-variations/8.png",
      "/facial-variations/9.png",
      "/facial-variations/10.png",
      "/facial-variations/11.png",
      "/facial-variations/12.png",
      "/facial-variations/13.png",
      "/facial-variations/14.png",
      "/facial-variations/15.png",
      "/facial-variations/16.png",
      "/facial-variations/17.png",
      "/facial-variations/18.png",
      "/facial-variations/19.png",
      "/facial-variations/20.png",
      "/facial-variations/21.png",
      "/facial-variations/22.svg",
      "/facial-variations/23.png",
      "/facial-variations/24.png",
    ],
  },
  {
    type: 2,
    name: "Clothes",
    assets: [
      "/clothes/0.png",
      "/clothes/1.png",
      "/clothes/2.png",
      "/clothes/3.png",
      "/clothes/4.png",
      "/clothes/5.png",
      "/clothes/6.png",
      "/clothes/7.png",
      "/clothes/8.png",
    ],
  },
  {
    type: 3,
    name: "Eyes",
    assets: [
      "/eyes/0.png",
      "/eyes/1.png",
      "/eyes/2.png",
      "/eyes/3.png",
      "/eyes/4.png",
      "/eyes/5.png",
      "/eyes/6.png",
    ],
  },
  {
    type: 4,
    name: "Glasses",
    assets: [
      "/glasses/0.png",
      "/glasses/1.png",
      "/glasses/2.png",
      "/glasses/3.png",
      "/glasses/4.png",
      "/glasses/5.png",
      "/glasses/6.png",
      "/glasses/7.png",
      "/glasses/8.png",
      "/glasses/9.png",
    ],
  },
  {
    type: 5,
    name: "Hair",
    assets: [
      "/hairs/0.png",
      "/hairs/1.png",
      "/hairs/2.png",
      "/hairs/3.png",
      "/hairs/4.png",
      "/hairs/5.png",
      "/hairs/6.png",
      "/hairs/7.png",
      "/hairs/8.png",
      "/hairs/9.png",
    ],
  },
  {
    type: 6,
    name: "Eye Brows",
    assets: [
      "/eye-brows/0.png",
      "/eye-brows/1.png",
      "/eye-brows/2.png",
      "/eye-brows/3.png",
      "/eye-brows/4.png",
      "/eye-brows/5.png",
      "/eye-brows/6.png",
      "/eye-brows/7.png",
      "/eye-brows/8.png",
    ],
  },
  {
    type: 7,
    name: "Ear accessory",
    assets: [
      "/ear-accessory/0.png",
      "/ear-accessory/1.png",
      "/ear-accessory/2.png",
      "/ear-accessory/3.png",
      "/ear-accessory/4.png",
      "/ear-accessory/5.png",
      "/ear-accessory/6.png",
      "/ear-accessory/7.png",
      "/ear-accessory/8.png",
      "/ear-accessory/9.png",
    ],
  },
  {
    type: 8,
    name: "Beards",
    assets: [
      "/beards/0.png",
      "/beards/1.png",
      "/beards/2.png",
      "/beards/3.png",
      "/beards/4.png",
    ],
  },
];
